import type { ThemeConfig } from '@/types'

const generateId = () => Math.random().toString(36).substring(2, 11)

export const PRESET_THEMES: ThemeConfig[] = [
  {
    id: 'aurora',
    name: '极光',
    description: '神秘的北极光渐变，带来梦幻般的视觉体验',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#a78bfa',
      secondary: '#60a5fa',
      accent: '#34d399',
      gradientStart: '#0f172a',
      gradientEnd: '#1e1b4b',
      background: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f766e 100%)',
      surface: 'rgba(30, 27, 75, 0.85)',
      textPrimary: '#f1f5f9',
      textSecondary: '#94a3b8',
      border: 'rgba(167, 139, 250, 0.3)',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa'
    },
    cardOpacity: 0.85,
    borderRadius: 16,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.6,
    mode: 'dark',
    tags: ['渐变', '梦幻', '深色', '自然']
  },
  {
    id: 'forest',
    name: '森林',
    description: '清新自然的森林色调，让你仿佛置身于大自然中',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#22c55e',
      secondary: '#16a34a',
      accent: '#84cc16',
      gradientStart: '#14532d',
      gradientEnd: '#052e16',
      background: 'linear-gradient(180deg, #14532d 0%, #166534 50%, #052e16 100%)',
      surface: 'rgba(20, 83, 45, 0.8)',
      textPrimary: '#f0fdf4',
      textSecondary: '#86efac',
      border: 'rgba(34, 197, 94, 0.3)',
      success: '#4ade80',
      warning: '#facc15',
      error: '#f87171',
      info: '#38bdf8'
    },
    cardOpacity: 0.8,
    borderRadius: 20,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.5,
    mode: 'dark',
    tags: ['自然', '清新', '绿色', '护眼']
  },
  {
    id: 'ocean',
    name: '海洋',
    description: '深邃的海洋蓝色调，带来宁静与放松的感觉',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#0ea5e9',
      secondary: '#0284c7',
      accent: '#06b6d4',
      gradientStart: '#0c4a6e',
      gradientEnd: '#164e63',
      background: 'linear-gradient(135deg, #0c4a6e 0%, #0369a1 50%, #164e63 100%)',
      surface: 'rgba(12, 74, 110, 0.85)',
      textPrimary: '#f0f9ff',
      textSecondary: '#7dd3fc',
      border: 'rgba(14, 165, 233, 0.3)',
      success: '#22d3ee',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#38bdf8'
    },
    cardOpacity: 0.85,
    borderRadius: 18,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.7,
    mode: 'dark',
    tags: ['海洋', '蓝色', '宁静', '深邃']
  },
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    description: '霓虹灯光与未来科技感的完美结合',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#f472b6',
      secondary: '#22d3ee',
      accent: '#a855f7',
      gradientStart: '#0f0a1f',
      gradientEnd: '#1a0b2e',
      background: 'linear-gradient(135deg, #0f0a1f 0%, #1a0b2e 50%, #0f0a1f 100%)',
      surface: 'rgba(15, 10, 31, 0.9)',
      textPrimary: '#fdf4ff',
      textSecondary: '#f0abfc',
      border: 'rgba(244, 114, 182, 0.4)',
      success: '#22d3ee',
      warning: '#facc15',
      error: '#fb7185',
      info: '#a855f7'
    },
    cardOpacity: 0.9,
    borderRadius: 8,
    fontFamily: "'JetBrains Mono', 'Consolas', monospace",
    shadowIntensity: 0.9,
    mode: 'dark',
    tags: ['霓虹', '科技', '未来', '电竞']
  },
  {
    id: 'minimal-white',
    name: '极简白',
    description: '简洁优雅的白色主题，适合办公和阅读',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#6366f1',
      secondary: '#8b5cf6',
      accent: '#ec4899',
      gradientStart: '#ffffff',
      gradientEnd: '#f8fafc',
      background: '#ffffff',
      surface: 'rgba(255, 255, 255, 0.95)',
      textPrimary: '#1e293b',
      textSecondary: '#64748b',
      border: 'rgba(99, 102, 241, 0.2)',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6'
    },
    cardOpacity: 0.95,
    borderRadius: 12,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.3,
    mode: 'light',
    tags: ['简约', '白色', '办公', '清新']
  },
  {
    id: 'deep-space',
    name: '深空黑',
    description: '纯净的深空黑色，节省电量同时保护眼睛',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#667eea',
      secondary: '#764ba2',
      accent: '#f093fb',
      gradientStart: '#0a0a0a',
      gradientEnd: '#111827',
      background: '#0a0a0a',
      surface: 'rgba(17, 24, 39, 0.95)',
      textPrimary: '#f9fafb',
      textSecondary: '#9ca3af',
      border: 'rgba(102, 126, 234, 0.3)',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6'
    },
    cardOpacity: 0.95,
    borderRadius: 16,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.8,
    mode: 'dark',
    tags: ['深色', '护眼', '省电', '纯净']
  },
  {
    id: 'sunset',
    name: '日落黄昏',
    description: '温暖的橙红色渐变，如傍晚的夕阳般美丽',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#f97316',
      secondary: '#fb923c',
      accent: '#f43f5e',
      gradientStart: '#7c2d12',
      gradientEnd: '#431407',
      background: 'linear-gradient(180deg, #7c2d12 0%, #ea580c 50%, #431407 100%)',
      surface: 'rgba(124, 45, 18, 0.8)',
      textPrimary: '#fff7ed',
      textSecondary: '#fdba74',
      border: 'rgba(249, 115, 22, 0.3)',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa'
    },
    cardOpacity: 0.8,
    borderRadius: 24,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.6,
    mode: 'dark',
    tags: ['温暖', '橙色', '日落', '浪漫']
  },
  {
    id: 'lavender',
    name: '薰衣草',
    description: '优雅的紫色调，带来浪漫与温馨的氛围',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#a855f7',
      secondary: '#c084fc',
      accent: '#f0abfc',
      gradientStart: '#faf5ff',
      gradientEnd: '#f3e8ff',
      background: 'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 50%, #fae8ff 100%)',
      surface: 'rgba(255, 255, 255, 0.9)',
      textPrimary: '#581c87',
      textSecondary: '#9333ea',
      border: 'rgba(168, 85, 247, 0.2)',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6'
    },
    cardOpacity: 0.9,
    borderRadius: 20,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.4,
    mode: 'light',
    tags: ['紫色', '浪漫', '优雅', '温馨']
  },
  {
    id: 'coffee',
    name: '咖啡时光',
    description: '浓郁的咖啡色调，适合午后休闲时光',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#a16207',
      secondary: '#ca8a04',
      accent: '#d97706',
      gradientStart: '#451a03',
      gradientEnd: '#78350f',
      background: 'linear-gradient(135deg, #451a03 0%, #78350f 50%, #451a03 100%)',
      surface: 'rgba(69, 26, 3, 0.85)',
      textPrimary: '#fef3c7',
      textSecondary: '#fcd34d',
      border: 'rgba(161, 98, 7, 0.4)',
      success: '#84cc16',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#38bdf8'
    },
    cardOpacity: 0.85,
    borderRadius: 16,
    fontFamily: "'Georgia', serif",
    shadowIntensity: 0.7,
    mode: 'dark',
    tags: ['咖啡', '棕色', '复古', '休闲']
  },
  {
    id: 'ice-mint',
    name: '冰薄荷',
    description: '清凉的薄荷绿色调，夏日里的一丝凉意',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#14b8a6',
      secondary: '#2dd4bf',
      accent: '#5eead4',
      gradientStart: '#ecfeff',
      gradientEnd: '#ccfbf1',
      background: 'linear-gradient(135deg, #ecfeff 0%, #ccfbf1 50%, #f0fdfa 100%)',
      surface: 'rgba(255, 255, 255, 0.9)',
      textPrimary: '#134e4a',
      textSecondary: '#0d9488',
      border: 'rgba(20, 184, 166, 0.2)',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6'
    },
    cardOpacity: 0.9,
    borderRadius: 18,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.3,
    mode: 'light',
    tags: ['清凉', '绿色', '夏日', '清新']
  },
  {
    id: 'midnight-blue',
    name: '午夜蓝',
    description: '深沉的午夜蓝色，适合夜间使用',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#3b82f6',
      secondary: '#6366f1',
      accent: '#8b5cf6',
      gradientStart: '#1e3a5f',
      gradientEnd: '#0f172a',
      background: 'linear-gradient(180deg, #1e3a5f 0%, #0f172a 100%)',
      surface: 'rgba(30, 58, 95, 0.9)',
      textPrimary: '#dbeafe',
      textSecondary: '#93c5fd',
      border: 'rgba(59, 130, 246, 0.3)',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa'
    },
    cardOpacity: 0.9,
    borderRadius: 14,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.8,
    mode: 'dark',
    tags: ['蓝色', '夜间', '专业', '商务']
  },
  {
    id: 'cherry-blossom',
    name: '樱花',
    description: '粉嫩的樱花色调，春日里的浪漫气息',
    author: '系统预设',
    version: '1.0.0',
    createdAt: Date.now(),
    isPreset: true,
    isFavorite: false,
    colors: {
      primary: '#ec4899',
      secondary: '#f472b6',
      accent: '#fb7185',
      gradientStart: '#fdf2f8',
      gradientEnd: '#fce7f3',
      background: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 50%, #fff1f2 100%)',
      surface: 'rgba(255, 255, 255, 0.95)',
      textPrimary: '#831843',
      textSecondary: '#be185d',
      border: 'rgba(236, 72, 153, 0.2)',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6'
    },
    cardOpacity: 0.95,
    borderRadius: 24,
    fontFamily: "'Inter', -apple-system, sans-serif",
    shadowIntensity: 0.4,
    mode: 'light',
    tags: ['粉色', '樱花', '浪漫', '春天']
  }
]

export const DEFAULT_THEME: ThemeConfig = PRESET_THEMES[5]

export const WEATHER_THEME_ADJUSTMENTS: Record<string, Partial<ThemeConfig['colors']>> = {
  sunny: {
    primary: '#f59e0b',
    accent: '#fbbf24',
    gradientStart: '#fef3c7',
    gradientEnd: '#fde68a'
  },
  cloudy: {
    primary: '#64748b',
    accent: '#94a3b8',
    gradientStart: '#f1f5f9',
    gradientEnd: '#e2e8f0'
  },
  rainy: {
    primary: '#3b82f6',
    accent: '#60a5fa',
    gradientStart: '#1e3a5f',
    gradientEnd: '#0f172a'
  },
  snowy: {
    primary: '#e2e8f0',
    accent: '#f8fafc',
    gradientStart: '#f1f5f9',
    gradientEnd: '#e2e8f0'
  },
  windy: {
    primary: '#0ea5e9',
    accent: '#38bdf8',
    gradientStart: '#e0f2fe',
    gradientEnd: '#bae6fd'
  },
  foggy: {
    primary: '#6b7280',
    accent: '#9ca3af',
    gradientStart: '#f3f4f6',
    gradientEnd: '#d1d5db'
  },
  thunderstorm: {
    primary: '#7c3aed',
    accent: '#a855f7',
    gradientStart: '#1e1b4b',
    gradientEnd: '#0f0a1f'
  }
}

export const HOLIDAY_THEMES = [
  {
    id: 'spring-festival',
    name: '春节限定',
    holiday: '春节',
    startDate: '01-20',
    endDate: '02-05',
    theme: {
      id: 'spring-festival',
      name: '春节限定',
      description: '红红火火过新年',
      author: '系统',
      version: '1.0.0',
      createdAt: Date.now(),
      isPreset: true,
      isFavorite: false,
      colors: {
        primary: '#dc2626',
        secondary: '#f97316',
        accent: '#fbbf24',
        gradientStart: '#7f1d1d',
        gradientEnd: '#991b1b',
        background: 'linear-gradient(135deg, #7f1d1d 0%, #dc2626 50%, #991b1b 100%)',
        surface: 'rgba(127, 29, 29, 0.9)',
        textPrimary: '#fef2f2',
        textSecondary: '#fecaca',
        border: 'rgba(220, 38, 38, 0.4)',
        success: '#22c55e',
        warning: '#fbbf24',
        error: '#f87171',
        info: '#3b82f6'
      },
      cardOpacity: 0.9,
      borderRadius: 16,
      fontFamily: "'Noto Serif SC', serif",
      shadowIntensity: 0.8,
      mode: 'dark',
      tags: ['春节', '红色', '喜庆', '限定']
    } as ThemeConfig,
    isActive: false
  },
  {
    id: 'christmas',
    name: '圣诞限定',
    holiday: '圣诞节',
    startDate: '12-20',
    endDate: '12-26',
    theme: {
      id: 'christmas',
      name: '圣诞限定',
      description: '温馨的圣诞节日氛围',
      author: '系统',
      version: '1.0.0',
      createdAt: Date.now(),
      isPreset: true,
      isFavorite: false,
      colors: {
        primary: '#166534',
        secondary: '#dc2626',
        accent: '#fbbf24',
        gradientStart: '#14532d',
        gradientEnd: '#166534',
        background: 'linear-gradient(135deg, #14532d 0%, #166534 50%, #15803d 100%)',
        surface: 'rgba(20, 83, 45, 0.9)',
        textPrimary: '#f0fdf4',
        textSecondary: '#86efac',
        border: 'rgba(22, 101, 52, 0.4)',
        success: '#22c55e',
        warning: '#fbbf24',
        error: '#dc2626',
        info: '#3b82f6'
      },
      cardOpacity: 0.9,
      borderRadius: 20,
      fontFamily: "'Inter', -apple-system, sans-serif",
      shadowIntensity: 0.7,
      mode: 'dark',
      tags: ['圣诞', '绿色', '红色', '限定']
    } as ThemeConfig,
    isActive: false
  },
  {
    id: 'halloween',
    name: '万圣节限定',
    holiday: '万圣节',
    startDate: '10-28',
    endDate: '11-01',
    theme: {
      id: 'halloween',
      name: '万圣节限定',
      description: '神秘诡异的万圣节主题',
      author: '系统',
      version: '1.0.0',
      createdAt: Date.now(),
      isPreset: true,
      isFavorite: false,
      colors: {
        primary: '#f97316',
        secondary: '#7c3aed',
        accent: '#16a34a',
        gradientStart: '#1c1917',
        gradientEnd: '#292524',
        background: 'linear-gradient(135deg, #1c1917 0%, #292524 50%, #1c1917 100%)',
        surface: 'rgba(28, 25, 23, 0.95)',
        textPrimary: '#fed7aa',
        textSecondary: '#fdba74',
        border: 'rgba(249, 115, 22, 0.4)',
        success: '#16a34a',
        warning: '#f97316',
        error: '#dc2626',
        info: '#7c3aed'
      },
      cardOpacity: 0.95,
      borderRadius: 12,
      fontFamily: "'Creepster', cursive",
      shadowIntensity: 0.9,
      mode: 'dark',
      tags: ['万圣节', '橙色', '神秘', '限定']
    } as ThemeConfig,
    isActive: false
  }
]

export const FONT_FAMILIES = [
  { label: '系统默认', value: "'Inter', -apple-system, sans-serif" },
  { label: '衬线体', value: "'Georgia', serif" },
  { label: '无衬线体', value: "'Helvetica Neue', Arial, sans-serif" },
  { label: '等宽字体', value: "'JetBrains Mono', 'Consolas', monospace" },
  { label: '圆体', value: "'Nunito', sans-serif" }
]

export const generateThemeId = generateId
